articles/urls.py
from django.urls import path
from . import views

app_name = "article"
urlpatterns = [
    path('', views.articles_list , name="list"),
    path('<slug>', views.articles_details , name="detail")
]

myblog/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about , name='about'),
    path('', views.home , name='home'),
    path('articles/', include('articles.urls')),
]

urlpatterns += staticfiles_urlpatterns()

articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.body[:50 ] + ' ...'

articles/views.py
from django.shortcuts import render, HttpResponse
from . import models

def articles_list(request):
    articles = models.Article.objects.all().order_by('date')
    args = {'articles':articles}
    return render(request,'articles/articles_list.html',args)

def articles_details(request, slug):
    return HttpResponse(slug)

myblog/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

def about(request):
    #return HttpResponse('hi, How are you')
    return render(request,'about.html')

def home(request):
    #return HttpResponse('home  home   home')
    return render(request,'home.html')

articles/templates/articles/articles_list.html
{%extends 'base.html'%}

{% block title %}
articles
{% endblock %}

{% block content %}
        
    <div>      
    <h1><P>articles</P></h1>
    {% for article in articles %}
        <h2>
            <a href="{% url "article:detail" slug=article.slug  %}">{{article.title}}</a>
            <p>{{ article.snippet }}</p>
            <p>{{ article.date }}</p>
        </h2>
        {% endfor %}
    </div>
{% endblock content %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>broozblog/about</title>
</head>
<body>
    about me : من یک برنامه نویس هستم
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>articles</title>
    {%endblock%}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body>
    <a href="http://localhost:8000/articles">logo</a>
    <div class="wrapper">
    {% block content %}
    {% endblock content %}
    </div>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>broozblog/home</title>
</head>
<body>
    <P>hone in home</P>
</body>
</html>